### ISSUE TITLE
Astaro Security Gateway - Target Service Not Allowed

### ISSUE THREAD

**Issue by PhilipMugglestone** [gregorwolf/hanatrial-auth-proxy#1]
Hi Gregor,

The auth-proxy part is working fine:
![image](https://cloud.githubusercontent.com/assets/10544432/5754830/039b4906-9c9e-11e4-8347-a877d4ec62b5.png)
![image](https://cloud.githubusercontent.com/assets/10544432/5754861/4da29d38-9c9e-11e4-9f0e-4dca085396ef.png)

Nearly have it working from destination - but getting 403 Forbidden / Astaro Security Gateway "Target service not allowed":
![image](https://cloud.githubusercontent.com/assets/10544432/5754879/9da3267c-9c9e-11e4-9b88-59d26e73b11a.png)

Suspect this could be something incorrect in the destination or cloud connector config?

Cloud Connector Config:
![image](https://cloud.githubusercontent.com/assets/10544432/5754938/39e2b4f8-9c9f-11e4-9a77-faaf777be0a1.png)

Destination Config:
![image](https://cloud.githubusercontent.com/assets/10544432/5754918/011fbc2e-9c9f-11e4-93ad-fd7a2c4612e1.png)

Seeing the same issue for WebIDE and HTML5 apps.

Thanks, 
Philip

**Comment by gregorwolf** [comment]
Dear Philip,

I think that the problem must be somewhere in the Proxy configuration of your Browser. The request you make to localhost:7891 via the hana-auth-proxy gets a valid response. So the hana-auth-proxy can reach the HANA Server in the Cloud (I have not yet implemented the possibility to configure a HTTP Proxy Server).

My SAP Cloud Connector configuration looks quite the same:

![screenshot at jan 15 11-19-16](https://cloud.githubusercontent.com/assets/2639535/5755813/1d55174a-9ca9-11e4-8ccd-1ddee54aa5b4.png)

![screenshot at jan 15 11-19-33](https://cloud.githubusercontent.com/assets/2639535/5755812/1d5493c4-9ca9-11e4-806c-0ec3c64bcc22.png)

Also the the destination looks fine:

![destination](https://cloud.githubusercontent.com/assets/2639535/5755911/20501f70-9caa-11e4-998f-1764091a8ab7.PNG)

Please check if you can de-activate the use of a Proxy in your Browser. This should then allow you to reach the destination via the HTML5 app. 

Just to make sure I'm asking that you have a valid neo-app.json with a route to the destination like:

{
  "welcomeFile": "index.html",
  "routes": [
    {
      "path": "/destinations/XSOdataCC",
      "target": {
        "type": "destination",
        "name": "XSOdataCC"
      },
      "description": "XSOdata via Cloud Connector and"
    }
  ]
}

Best regards
Gregor

**Comment by PhilipMugglestone** [comment]
Hi Gregor,

In fact the issue was down to incorrect configuration. 

After setting the destination's proxy type to "OnPremise":
![image](https://cloud.githubusercontent.com/assets/10544432/5757188/ff768654-9cb8-11e4-9bba-b31c3c31b35a.png)

And also using the trial account name in the Cloud Configuration URL path it works:
![image](https://cloud.githubusercontent.com/assets/10544432/5757193/0d7d064c-9cb9-11e4-8191-dd624226c102.png)

Many thanks,

Philip
