### ISSUE TITLE
Error: Invalid URI "/saml2/idp/sso/accounts.sap.com

### ISSUE THREAD

**Issue by didierheck** [gregorwolf/hanatrial-auth-proxy#10]
Hi Gregor, 
I was perfectly able to use your authentication proxy until now and here is the error message I receive today : 
... 
Get new session cookie 
[Error: Invalid URI "/saml2/idp/sso/accounts.sap.com"] 

Any idea where this might come from ? 
Thank in advance for your precious input. 
Regards, 
Didier

**Comment by didierheck** [comment]
Hana Cloud Connector is running.
As soon as I have entered my login/passwd requested by my app using the Destination using the auth-proxy through the HCC, I have these messages appearing
![proxyproblem](https://cloud.githubusercontent.com/assets/13241925/8602134/cbac6018-2670-11e5-8b90-51c1c857c69d.JPG)

**Comment by gregorwolf** [comment]
Hello Didier,

seems that SAP changed something on the authentication form. I'm debugging the issue.

Best regards
Gregor

**Comment by gregorwolf** [comment]
Have tried to figure out what's changed on HCP trial so it doesn't work anymore. The form at accounts.sap.com is submitted but not like in a real browser the user doesn't get authenticated. Instead the same form is displayed again. Unfortunately without any error message. @mlenkeit do you have any clue?

**Comment by ahmdsamir91** [comment]
Hello sir,
i had the same problem 10 days ago.
i tried to use it today and it worked just fine with me ^_^

**Comment by gregorwolf** [comment]
Seems it was an error with the SAP ID Service.
