### ISSUE TITLE
Getting an error " Can not set  property 'domain' of undefined

### ISSUE THREAD

**Issue by LakshmiDMohan** [gregorwolf/hanatrial-auth-proxy#11]
Hello Gregorwolf! Thank you so much for your software.

I am trying to call XSODATA from SAPUI5 application in HCP trial account.I am not successful with node.js I receive an error "cannot set property 'domain' of undefined. Node.js is updated last week. could the latest version has problem. I tried with the earlier versions and running into another messages.Can you please guide me ?

![image](https://cloud.githubusercontent.com/assets/13701810/10009959/1b405be0-60b2-11e5-8e30-94e3d3ae1cdf.png)
![image](https://cloud.githubusercontent.com/assets/13701810/10009963/32d90d2e-60b2-11e5-8742-2bb9f8fdd92d.png)

**Comment by gregorwolf** [comment]
Can you please execute:

`node -v`

and post the result so I know which exact version you're using. Also let me know about the errors you get with an earlier node version. I currently run fine on "v0.10.30".

**Comment by LakshmiDMohan** [comment]
Thanks for your prompt reply! Node -v is v4.1.0

I tried  with  v0.10.30 ran into other issues ..Will try it again and send you the screenshot

Thanks,
Lakshmi

**Comment by LakshmiDMohan** [comment]
Just wanted to let you know that I was previously getting the error below
![image](https://cloud.githubusercontent.com/assets/13701810/10016375/82c1a8e0-60f4-11e5-9d2b-dd8dd2aa9ed3.png). 

I could resolve it by following the solution  below given in this thread

Replace line
var request = require('request');
with
var request = require('C:/Program Files/nodejs/node_modules/npm/node_modules/request/request');

http://scn.sap.com/community/developer-center/front-end/blog/2015/03/18/how-to-consume-a-hana-xs-datasource-on-the-hana-trial-landscape

**Comment by LakshmiDMohan** [comment]
Hello GregorWolf,

It is now working with v0.10.30...Intially I got a an error object has not method 'Init'. I reverted the location for the 'request' I mentioned above.. I am now able to see the $metadata file.Thank you so much for the proxy!

![image](https://cloud.githubusercontent.com/assets/13701810/10016980/e0b59f84-60f8-11e5-8015-389d660fa045.png)

Thanks,
Lakshmi
