### ISSUE TITLE
install certificate for https request

### ISSUE THREAD

**Issue by techie-khushdeep** [gregorwolf/hanatrial-auth-proxy#13]
Hi,

I have installed openSSL by installer. and i have put the command as mention for key and certificate.
during creation of certificate i have given common name(domain name): s9hanaxs.hanatrial.ondemand.com.
after creation of certificate proxy-csr.pem.
i open above certificate in editor and copied the content on website - https://www.cacert.org -> server certificate-> New.
Then i have pasted my content in CSR area. after click on submission button i am getting following error : "The following hostnames were rejected because the system couldn't link them to your account, if they are valid please verify the domains against your account.
Rejected: s9hanaxs.hanatrial.ondemand.com".

is i have missed something ?
any further step to execute service https with proxy.

Regards,
Khushdeep Singh

**Comment by gregorwolf** [comment]
Dear Khushdeep,

please read through the instructions of CACert. The domain for which you want to create a certificate must be one that is linked in your account. That is not an issue with this project. So I close the incident.

Best regards
Gregor
