### ISSUE TITLE
Localhost returning 503

### ISSUE THREAD

**Issue by ghost** [gregorwolf/hanatrial-auth-proxy#16]
Hi,

After executing the server-basic-auth.js, and accessing the app via the localhost, I get the following : 

```
SAP HANA Cloud Trial Authentication Proxy for HANA XS Services ready: http://localhost:7891
GET /p1941959177trial/devv/live3/services.xsodata
Get new session cookie
Something went wrong: https://s17hanaxs.hanatrial.ondemand.com:/p1941959177trial/devv/live3/services.xsodata returned 503
```

How can I overcome this?

Appreciate your cooperation in advance. Thank you.

**Comment by gregorwolf** [comment]
When I request:

https://s17hanaxs.hanatrial.ondemand.com/p1941959177trial/devv/live3/services.xsodata

in my browser I get:

Service Unavailable

perhaps it's a problem on the HCP side. Please try again when the direct call is working.

**Comment by ghost** [comment]
I didn't quite get what you asked me to do.

I'm following the video tutorial series available on Youtube in the SAP HANA Academy. When I got to the 23rd video "Web Services - Authentication Setup Proxy" I get stuck in this step.

When I try to access the app data via localhost, I get the error I mentioned precedently.

**Comment by gregorwolf** [comment]
In the moment I would still guess that the URL you've provided:

https://s17hanaxs.hanatrial.ondemand.com/p1941959177trial/devv/live3/services.xsodata

is just simply not correct. Have you got this URL via testing the xsodata service using the SAP HANA Web-based Development Workbench? From the HCP Cockpit? Can you try accessing:

https://s2hanaxs.hanatrial.ondemand.com/s0001142741trial/xsdemo/hello/hello.xsjs

Does that work for you?

**Comment by ghost** [comment]
You were right. It was a stupid typo. Thank you for your time.
