### ISSUE TITLE
options.uri is a required argument

### ISSUE THREAD

**Issue by jojeda10** [gregorwolf/hanatrial-auth-proxy#18]
Hello Gregor,

Unfortunately I cannot change the status of this closed incident. I'm opening this one with a reference to issue #17 

I’ve installed your proxy on Node.js 6.2.0 (x64) in Windows 10.  Following Simmaco’s post I’ve created a couple of tables and a related OData service in Hana XS of my HCP Trial account.

It works well under URL _https://devs0005549254trial.hanatrial.ondemand.com/s0005549254trial/dev/myproducts/services.xsodata/$metadata_

![1](https://cloud.githubusercontent.com/assets/8849468/15453453/f29f7f84-2016-11e6-9547-cbb257d63f62.png)

I changed the config.js file to set my host
![2](https://cloud.githubusercontent.com/assets/8849468/15453458/3a3575a6-2017-11e6-91e7-2b5858681981.png)

I can then start the proxy in Node.js console
![3](https://cloud.githubusercontent.com/assets/8849468/15453462/429d4ce6-2017-11e6-9d68-435243f6ed66.png)

But when I call the URL the browser hangs and the console displays following

_http://localhost:7891/s0005549254trial/dev/myproducts/services.xsodata/$metadata_

![4](https://cloud.githubusercontent.com/assets/8849468/15453463/4bd1a1e0-2017-11e6-821a-cb84f3213815.png)

If I console log the URL used in options in hana_saml.js I see action reaches as undefined 
![3b](https://cloud.githubusercontent.com/assets/8849468/15453465/6c51d7f0-2017-11e6-888c-cf7dae0ed6d0.png)

![5](https://cloud.githubusercontent.com/assets/8849468/15453468/718cff2e-2017-11e6-8934-f4c28bd7d13e.png)
Unfortunately I cannot figure out from where that comes…

Thanks a lot for having a look at this. Please do not hesitate to ask me if you need any other detail to reproduce this scenario.

Best Regards,
Jaime

**Comment by gregorwolf** [comment]
Hi Jamie,

you don't need the hanatrial-auth-proxy when you're using the HANA MDC (<trial>). You only need it when using HANA XS (<shared>). With the MDC you should be able to set Basic authentication as documented here [Application-Access File Keyword Options](https://help.sap.com/saphelp_hanaplatform/helpdata/en/a9/fc5c220d744180850996e2f5d34d6c/content.htm).

Best regards
Gregor

**Comment by jojeda10** [comment]
Hi Gregor,

You are completely right. I was mistaken thinking the hanatrial-auth-proxy is still necessay when using the HANA MDC.

Sorry for the misunderstanding and once again thanks for your help!

Best Regards,
Jaime
