### ISSUE TITLE
can not set hanatrial-auth-proxy- error : can not find module 'request'......

### ISSUE THREAD

**Issue by sirajafridi** [gregorwolf/hanatrial-auth-proxy#5]
Hi, Gregor!
I followed your mentioned setting for hanatrial-auth-proxy but it give me error message.
![image](https://cloud.githubusercontent.com/assets/11664279/6847022/aa1872a2-d3dc-11e4-880b-f0f1f7fbc647.png)
And also I did the pre-requisite. successfully installed cheerio and querystring using npm install command and made changes in config.js file (properly changed the host name). And  then used node server-basic-auth.js command which give me error message. can not find module 'request'......
Appreciate your cooperation in advance.Thanks

**Comment by gregorwolf** [comment]
Hi,
I forgot to add the node module request as a new requirement to the readme. I've fixed that in the commit 655f4e717405d7a2b8210d4f32f853be87eebdbc.
Best regards
Gregor

**Comment by sirajafridi** [comment]
Problem is fixed. Thank you.
